name: first CI/CD

on:
  pull_request:
    branches:
      - main
jobs:
  welcome_script:
    runs-on: ubuntu-latest
    steps:
    - name: Welcome part
      run: echo "Hello"
    - name: Get info
      run: |
        echo "Getting info..."
        whoami
        sleep 10
        pwd